### ISSUE TITLE
ctrl+c lors du téléchargement du template

### ISSUE THREAD

**Issue by rcastagnet** [n0vember/nocloud#16]
Bonjour,

Après avoir fait un ctrl+c lors du téléchargement du template ("vmtemplate -d debian8"), j'ai voulu relancer le téléchargement du template et vmtemplate m'a dit que le template existait déjà alors que j'avais arrété avant la fin. Est-ce normal ?

Merci,
Romain

**Comment by n0vember** [comment]
Tu peux ctrl+c autant que tu veux, maintenant ;)

**Comment by rcastagnet** [comment]
merci :)
