### ISSUE TITLE
Odd stuff in doc

### ISSUE THREAD

**Issue by pgrange** [n0vember/nocloud#31]
Documentation states that:
> You can then stop your VMs using (-d option destroys the machines) :
> 
> nocloud destroy

This is strange to have a -d option (not used in command) that is supposed to destroy machines and see _destroy_ in the command in documentation.

**Comment by n0vember** [comment]
This is a bad adaptation in the recent migration from vm commands to nocloud single command.

This is fixed by 14603ec
