### ISSUE TITLE
Bug in doc ?

### ISSUE THREAD

**Issue by pgrange** [n0vember/nocloud#32]
I think ```run``` is missing from this command line in documentation and this is odd to see ```daemon``` option but read that it will stay in foreground.

> Alternatively, you can launch your description file using daemon mode
>
> nocloud file pftest daemon
>
>It will stay in foreground and log (hopefuly) useful information until you press ^C which will make it kill and destroy all its machines.

**Comment by n0vember** [comment]
Daemon mode indeed. When you run nocloud command it normally run VM in the background and give you back your shell. Daemon mode is meant to be run by a service. Service can then use nocloud ouput as log.

But I understand the misunderstanding and I am to rename this option.

As for the missing run it is indeed missing and will be added.

**Comment by n0vember** [comment]
missing run fixed : a1aa2fd

**Comment by n0vember** [comment]
daemon mode renamed : 19b0d38
