### ISSUE TITLE
Network forwarding rules

### ISSUE THREAD

**Issue by pgrange** [n0vember/nocloud#9]
I think the following iptables rules should be set by the nocloud service (bridge ?) :

```
sudo iptables -I INPUT -i nocloud -j ACCEPT
sudo iptables -N fw-interfaces
sudo iptables -A FORWARD -j fw-interfaces
sudo iptables -A fw-interfaces -i nocloud -j ACCEPT
sudo iptables -t nat -A POSTROUTING -s 192.168.1.0/24 ! -o nocloud -j MASQUERADE
sudo iptables -A FORWARD -o nocloud -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
```

May be fw-interfaces should have a more specific name.

**Comment by n0vember** [comment]
I add to change rules order (-I instead of -A for some rules) but I implemented this and removed it from documentation. Also fw-interfaces is now known as NOCLOUD, which may be a bit more explicit :)

git pull, sudo make and let me know if this does the job for you.
